/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as VisitorRouteImport } from './routes/_visitor'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCandidateRouteImport } from './routes/_authenticated/candidate'
import { Route as AuthenticatedRecruiterRouteImport } from './routes/_authenticated/recruiter'
import { Route as VisitorLoginRouteImport } from './routes/_visitor/login'
import { Route as VisitorRegisterRouteImport } from './routes/_visitor/register'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedCandidateIndexRouteImport } from './routes/_authenticated/candidate/index'
import { Route as AuthenticatedCandidateDashboardRouteImport } from './routes/_authenticated/candidate/dashboard'
import { Route as AuthenticatedRecruiterIndexRouteImport } from './routes/_authenticated/recruiter/index'
import { Route as AuthenticatedRecruiterDashboardRouteImport } from './routes/_authenticated/recruiter/dashboard'
import { Route as AuthenticatedRecruiterJobsIndexRouteImport } from './routes/_authenticated/recruiter/jobs/index'
import { Route as AuthenticatedRecruiterJobsNewRouteImport } from './routes/_authenticated/recruiter/jobs/new'
import { Route as AuthenticatedRecruiterJobsJobIdEditRouteImport } from './routes/_authenticated/recruiter/jobs/$jobId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorRoute = VisitorRouteImport.update({
  id: '/_visitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCandidateRoute = AuthenticatedCandidateRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecruiterRoute = AuthenticatedRecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const VisitorLoginRoute = VisitorLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => VisitorRoute,
} as any)
const VisitorRegisterRoute = VisitorRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => VisitorRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCandidateIndexRoute =
  AuthenticatedCandidateIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCandidateRoute,
  } as any)
const AuthenticatedCandidateDashboardRoute =
  AuthenticatedCandidateDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedCandidateRoute,
  } as any)
const AuthenticatedRecruiterIndexRoute =
  AuthenticatedRecruiterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterDashboardRoute =
  AuthenticatedRecruiterDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterJobsIndexRoute =
  AuthenticatedRecruiterJobsIndexRouteImport.update({
    id: '/jobs/',
    path: '/jobs/',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterJobsNewRoute =
  AuthenticatedRecruiterJobsNewRouteImport.update({
    id: '/jobs/new',
    path: '/jobs/new',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterJobsJobIdEditRoute =
  AuthenticatedRecruiterJobsJobIdEditRouteImport.update({
    id: '/jobs/$jobId/edit',
    path: '/jobs/$jobId/edit',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/candidate': typeof AuthenticatedCandidateRouteWithChildren
  '/recruiter': typeof AuthenticatedRecruiterRouteWithChildren
  '/login': typeof VisitorLoginRoute
  '/register': typeof VisitorRegisterRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/candidate/dashboard': typeof AuthenticatedCandidateDashboardRoute
  '/recruiter/dashboard': typeof AuthenticatedRecruiterDashboardRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/candidate/': typeof AuthenticatedCandidateIndexRoute
  '/recruiter/': typeof AuthenticatedRecruiterIndexRoute
  '/recruiter/jobs/new': typeof AuthenticatedRecruiterJobsNewRoute
  '/recruiter/jobs/': typeof AuthenticatedRecruiterJobsIndexRoute
  '/recruiter/jobs/$jobId/edit': typeof AuthenticatedRecruiterJobsJobIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof VisitorLoginRoute
  '/register': typeof VisitorRegisterRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/candidate/dashboard': typeof AuthenticatedCandidateDashboardRoute
  '/recruiter/dashboard': typeof AuthenticatedRecruiterDashboardRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/candidate': typeof AuthenticatedCandidateIndexRoute
  '/recruiter': typeof AuthenticatedRecruiterIndexRoute
  '/recruiter/jobs/new': typeof AuthenticatedRecruiterJobsNewRoute
  '/recruiter/jobs': typeof AuthenticatedRecruiterJobsIndexRoute
  '/recruiter/jobs/$jobId/edit': typeof AuthenticatedRecruiterJobsJobIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_visitor': typeof VisitorRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/candidate': typeof AuthenticatedCandidateRouteWithChildren
  '/_authenticated/recruiter': typeof AuthenticatedRecruiterRouteWithChildren
  '/_visitor/login': typeof VisitorLoginRoute
  '/_visitor/register': typeof VisitorRegisterRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/candidate/dashboard': typeof AuthenticatedCandidateDashboardRoute
  '/_authenticated/recruiter/dashboard': typeof AuthenticatedRecruiterDashboardRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/candidate/': typeof AuthenticatedCandidateIndexRoute
  '/_authenticated/recruiter/': typeof AuthenticatedRecruiterIndexRoute
  '/_authenticated/recruiter/jobs/new': typeof AuthenticatedRecruiterJobsNewRoute
  '/_authenticated/recruiter/jobs/': typeof AuthenticatedRecruiterJobsIndexRoute
  '/_authenticated/recruiter/jobs/$jobId/edit': typeof AuthenticatedRecruiterJobsJobIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/admin'
    | '/candidate'
    | '/recruiter'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/candidate/dashboard'
    | '/recruiter/dashboard'
    | '/admin/'
    | '/candidate/'
    | '/recruiter/'
    | '/recruiter/jobs/new'
    | '/recruiter/jobs/'
    | '/recruiter/jobs/$jobId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/candidate/dashboard'
    | '/recruiter/dashboard'
    | '/admin'
    | '/candidate'
    | '/recruiter'
    | '/recruiter/jobs/new'
    | '/recruiter/jobs'
    | '/recruiter/jobs/$jobId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_visitor'
    | '/forbidden'
    | '/_authenticated/admin'
    | '/_authenticated/candidate'
    | '/_authenticated/recruiter'
    | '/_visitor/login'
    | '/_visitor/register'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/candidate/dashboard'
    | '/_authenticated/recruiter/dashboard'
    | '/_authenticated/admin/'
    | '/_authenticated/candidate/'
    | '/_authenticated/recruiter/'
    | '/_authenticated/recruiter/jobs/new'
    | '/_authenticated/recruiter/jobs/'
    | '/_authenticated/recruiter/jobs/$jobId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  VisitorRoute: typeof VisitorRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_visitor': {
      id: '/_visitor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof VisitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/candidate': {
      id: '/_authenticated/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof AuthenticatedCandidateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recruiter': {
      id: '/_authenticated/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof AuthenticatedRecruiterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_visitor/login': {
      id: '/_visitor/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof VisitorLoginRouteImport
      parentRoute: typeof VisitorRoute
    }
    '/_visitor/register': {
      id: '/_visitor/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof VisitorRegisterRouteImport
      parentRoute: typeof VisitorRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/candidate/': {
      id: '/_authenticated/candidate/'
      path: '/'
      fullPath: '/candidate/'
      preLoaderRoute: typeof AuthenticatedCandidateIndexRouteImport
      parentRoute: typeof AuthenticatedCandidateRoute
    }
    '/_authenticated/candidate/dashboard': {
      id: '/_authenticated/candidate/dashboard'
      path: '/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof AuthenticatedCandidateDashboardRouteImport
      parentRoute: typeof AuthenticatedCandidateRoute
    }
    '/_authenticated/recruiter/': {
      id: '/_authenticated/recruiter/'
      path: '/'
      fullPath: '/recruiter/'
      preLoaderRoute: typeof AuthenticatedRecruiterIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/dashboard': {
      id: '/_authenticated/recruiter/dashboard'
      path: '/dashboard'
      fullPath: '/recruiter/dashboard'
      preLoaderRoute: typeof AuthenticatedRecruiterDashboardRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/jobs/': {
      id: '/_authenticated/recruiter/jobs/'
      path: '/jobs'
      fullPath: '/recruiter/jobs/'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/jobs/new': {
      id: '/_authenticated/recruiter/jobs/new'
      path: '/jobs/new'
      fullPath: '/recruiter/jobs/new'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsNewRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/jobs/$jobId/edit': {
      id: '/_authenticated/recruiter/jobs/$jobId/edit'
      path: '/jobs/$jobId/edit'
      fullPath: '/recruiter/jobs/$jobId/edit'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsJobIdEditRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCandidateRouteChildren {
  AuthenticatedCandidateDashboardRoute: typeof AuthenticatedCandidateDashboardRoute
  AuthenticatedCandidateIndexRoute: typeof AuthenticatedCandidateIndexRoute
}

const AuthenticatedCandidateRouteChildren: AuthenticatedCandidateRouteChildren =
  {
    AuthenticatedCandidateDashboardRoute: AuthenticatedCandidateDashboardRoute,
    AuthenticatedCandidateIndexRoute: AuthenticatedCandidateIndexRoute,
  }

const AuthenticatedCandidateRouteWithChildren =
  AuthenticatedCandidateRoute._addFileChildren(
    AuthenticatedCandidateRouteChildren,
  )

interface AuthenticatedRecruiterRouteChildren {
  AuthenticatedRecruiterDashboardRoute: typeof AuthenticatedRecruiterDashboardRoute
  AuthenticatedRecruiterIndexRoute: typeof AuthenticatedRecruiterIndexRoute
  AuthenticatedRecruiterJobsNewRoute: typeof AuthenticatedRecruiterJobsNewRoute
  AuthenticatedRecruiterJobsIndexRoute: typeof AuthenticatedRecruiterJobsIndexRoute
  AuthenticatedRecruiterJobsJobIdEditRoute: typeof AuthenticatedRecruiterJobsJobIdEditRoute
}

const AuthenticatedRecruiterRouteChildren: AuthenticatedRecruiterRouteChildren =
  {
    AuthenticatedRecruiterDashboardRoute: AuthenticatedRecruiterDashboardRoute,
    AuthenticatedRecruiterIndexRoute: AuthenticatedRecruiterIndexRoute,
    AuthenticatedRecruiterJobsNewRoute: AuthenticatedRecruiterJobsNewRoute,
    AuthenticatedRecruiterJobsIndexRoute: AuthenticatedRecruiterJobsIndexRoute,
    AuthenticatedRecruiterJobsJobIdEditRoute:
      AuthenticatedRecruiterJobsJobIdEditRoute,
  }

const AuthenticatedRecruiterRouteWithChildren =
  AuthenticatedRecruiterRoute._addFileChildren(
    AuthenticatedRecruiterRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCandidateRoute: typeof AuthenticatedCandidateRouteWithChildren
  AuthenticatedRecruiterRoute: typeof AuthenticatedRecruiterRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCandidateRoute: AuthenticatedCandidateRouteWithChildren,
  AuthenticatedRecruiterRoute: AuthenticatedRecruiterRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface VisitorRouteChildren {
  VisitorLoginRoute: typeof VisitorLoginRoute
  VisitorRegisterRoute: typeof VisitorRegisterRoute
}

const VisitorRouteChildren: VisitorRouteChildren = {
  VisitorLoginRoute: VisitorLoginRoute,
  VisitorRegisterRoute: VisitorRegisterRoute,
}

const VisitorRouteWithChildren =
  VisitorRoute._addFileChildren(VisitorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  VisitorRoute: VisitorRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
